---
name: Trivy Java DB
on:
  schedule:
    - cron: "0 0 * * *" # update indexes every day in 00:00 
env:
  GH_USER: aqua-bot
  packages: write # for GHCR
  contents: read
jobs:
  build:
    name: Build DB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [3.5, 3.4]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Get DB version
        id: get_version
        run: echo "::set-output name=DB_VERSION::$(go run version.go)"
      

      - name: Build the binary
        run: make build

      - name: Crawl indexes
        run: make db-crawl

      - name: Build database
        run: make db-build

      - name: Compress database
        run: make db-compress

      - name: Move DB
        run: mv cache/db/javadb.tar.gz .

      - name: Login to GitHub Packages Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.JAVADB_GH_REGISTRY_TOKEN }}

      - name: Upload assets to GHCR
        env:
          DB_VERSION: ${{ steps.get_version.outputs.DB_VERSION }}
        run: |
          oras version
          oras push --artifact-type application/vnd.aquasec.trivy.config.v1+json \
          ghcr.io/${{ github.repository }}:${DB_VERSION} \
          javadb.tar.gz:application/vnd.aquasec.trivy.javadb.layer.v1.tar+gzip
